### ISSUE TITLE
咨询如何添加到fresh的showcase

### ISSUE THREAD

**Issue by shijianzhong** [kuizuo/link-maker#1]
同学你好
       看到你的站点添加到了fresh的showcase上，想咨询下如何添加，
我在执行deno task screenshot 的时候报改命令不存错
 deno task screenshot
Task not found: screenshot
Available tasks:
- start

**Comment by kuizuo** [comment]
提示 Task not found: screenshot 说明你当前运行目录下的 deno.json 文件中的 tasks 属性并没有 screenshot 命令，你需要确保 **执行 `deno task screenshot` 时的运行目录是 fresh 的根目录，而不是 www 目录**

当你执行完该命令后，会在 `www/static/showcase` 下生成对应尺寸的图片用于展示，然后你只需要把你的站点信息配置到`www/data/showcase.json` 下，这一部分的配置可以参考他人的pr，比如我的 [commit 记录](https://github.com/denoland/fresh/commit/c05b19387b76b679274139e71abefe49491a6dac)。

**Comment by shijianzhong** [comment]
谢谢，已经添加完毕
